version: "3.9"
services:
    nuxt-app:
        build: .
        container_name: nuxt-app
        ports:
            - "3000:3000"

networks:
    default:
        external: true
        name: ${APP_DOCKER_NETWORK}
