version: "3.9"
services:

    nuxt:
        container_name: front
        build: .
        ports:
            - "${APP_PORT-80}:3000"

networks:
    default:
        external: true
        name: production
